config/routes.rb
Rails.application.routes.draw do

  post 'checkout', to: 'items#sale' 

  resources :items

  get 'items/new'

  get 'users/new'

  root 'items#index'

  get  '/help',    to: 'static_pages#help'

  get  '/faq',    to: 'static_pages#faq'

  get  '/apply',    to: 'static_pages#apply'

  get  '/account',    to: 'users#new'

  get  '/checkout',    to: 'static_pages#checkout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  protect_from_forgery


  require "rubygems"
  require "braintree"

  Braintree::Configuration.environment = :sandbox
  Braintree::Configuration.merchant_id = ENV['MERCHANT_ID']
  Braintree::Configuration.public_key = ENV['PUBLIC_KEY']
  Braintree::Configuration.private_key = ENV['PRIVATE_KEY']



  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @token = Braintree::ClientToken.generate
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
        respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sale
    nonce = params[:payment_method_nonce]
    result = Braintree::Transaction.sale(
    :amount => "10.00", #could be any other arbitrary amount captured in params[:amount] if they weren't all $10.
    :payment_method_nonce => nonce,
    :options => {
      :submit_for_settlement => true
      }
    )
  end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :image_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def faq
  end

  def apply
  end

  def account
  end

  def checkout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "JUSTSMURF"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p>
<img src="https://www.unrankedsmurfs.com/images/upload/blog/2017/01/unranked.png" />
</p>
<h2>10$</h2>

<a href="items/5">item1</a>
<a href="items/6">item2</a>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_new_path %>

app/views/items/sale.html.erb
yay

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <img src="<%= @item.image_url %>" />
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

<form id="checkout" method="post" action="/checkout">
  <div id="payment-form"></div>
  <input type="submit" value="Pay $10">
</form>

<script src="https://js.braintreegateway.com/js/braintree-2.20.0.min.js"></script>
<script>
// We generated a client token for you so you can test out this code
// immediately. In a production-ready integration, you will need to
// generate a client token on your server (see section below).
var clientToken = "<%= @token %>";

braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Apply for a job with us",   apply_path %></li>
      <li><%= link_to "Frequently asked questions", faq_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "justsmurf", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-center">
            <li><%= link_to "ACCOUNT", account_path %></li>
            <li><%= link_to "CHECKOUT", checkout_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/apply.html.erb
<% provide(:title, "apply") %>
<h1>JUST SMURF</h1>
<p>
Apply for a job
</p>

app/views/static_pages/checkout.html.erb
<% provide(:title, "checkout") %>
<h1>JUST SMURF</h1>
<p>
checkout
</p>

app/views/static_pages/faq.html.erb
<% provide(:title, "faq") %>
<h1>JUST SMURF</h1>
<p>
faq
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "help") %>
<h1>JUST SMURF</h1>
<p>
Help
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "home") %>
<div class="center jumbotron">
  <h1>JUSTSMURF</h1>

  <h2>
	Homepage
  </h2>

  <%= link_to "Sign up now!", account_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'account') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>